### ISSUE TITLE
atm9 crash Version: 1.20.1-0.2.0-neoforge

### ISSUE THREAD

**Issue by jaynotgay** [Gilded-Games/Nitrogen#19] opened 2023-12-13 16:08 UTC
https://mclo.gs/t0CNGjy

**Comment by EnterFor** [comment] 2023-12-13 17:29
same

**Comment by bconlon1** [comment] 2023-12-13 17:35
Duplicate of #18

**Closed as not planned by bconlon1** 2023-12-13 17:35 UTC
Labels: priority/high, type/crash

**Comment by bconlon1** [comment] 2023-12-13 18:41
@jaynotgay add this to the mods folder:

https://output.circle-artifacts.com/output/job/92c27415-5941-460b-931f-2168381f231a/artifacts/0/~/project/build/libs/nitrogen_internals-1.20.1-0.2.0-neoforge.jar

Let me know if it works.
